[package]
name = "ffrostflame/bridgenet"
version = "1.9.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A feature-packed networking library oriented towards optimization and ease of usage."
license = "MIT"

[dependencies]
GoodSignal = "stravant/goodsignal@0.2.1"
Promise = "evaera/promise@4.0.0"